spring:
  datasource:
    url: jdbc:postgresql://47.118.23.183:5432/test
#    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: zAzHHplnxXb7QvT02QMl0oPV
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  sql:
    init:
      mode: never
  ai:
    dashscope:
      api-key: test-dashscope-key
    siliconflow:
      api-url: https://api.siliconflow.cn/v1/embeddings
      api-key: sk-qsbfrbnsojrkaapifyzvuvfoejsxstpbbokgxngjkzsinabu
      model: Qwen/Qwen3-Embedding-8B
      encoding-format: float
      dimensions: 1536
      rerank:
        api-url: https://api.siliconflow.cn/v1/rerank
        api-key: sk-qsbfrbnsojrkaapifyzvuvfoejsxstpbbokgxngjkzsinabu
        model: Qwen/Qwen3-Reranker-8B
        instruction: Please rerank the documents based on the query.
        top-n: 5
        return-documents: true
    generic-chat:
      api-url: https://api.siliconflow.cn/v1/chat/completions
      api-key: sk-qsbfrbnsojrkaapifyzvuvfoejsxstpbbokgxngjkzsinabu
      model: deepseek-ai/DeepSeek-V3.1-Terminus
      temperature: 0.7
      top-p: 0.7
      top-k: 50
      max-tokens: 4096
      frequency-penalty: 0.0
      n: 1
      stream: false
      enable-thinking: false
      thinking-budget: 4096
      connect-timeout: PT5S
      read-timeout: PT20S
    vectorstore:
      pgvector:
#        initialize-schema: true
        initialize-schema: false
        table-name: rag_chunks
        schema-name: public
        id-type: text
logging:
  level:
    org.springframework.jdbc.core: DEBUG   # 打印 JDBC SQL
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE # 打印参数绑定

# Prompt 配置默认值
prompt:
  template: classpath:prompts/dynamic_prompt_template.txt
  defaults:
    persona: 测试默认角色
    channel: 测试渠道